from . import emp_model
from . import emp_tag
from . import designation
from . import emp_documents
from . import emp_contract
from . import personal_info
from . import sale_model_field
from . import city
from . import product_supplierinfo_inherit
from . import res_emp_config_setting
from . import report_abstract_model
